version: '3.9'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
    networks:
      - mynetwork

networks:
  mynetwork:
